// mockData.js
export const lessonsData = {
  categories: [
    {
      id: 'onboarding',
      name: 'Onboarding',
      description: 'Essential foundations for new team members',
      totalLessons: 5,
      completedLessons: 3,
      color: 'blue',
      lessons: [
        {
          id: '100007',
          title: 'Welcome on board',
          dateRange: 'Nov 21 23...Nov 22 23',
          progress: 100,
          status: 'completed',
          tasks: [
            { id: 1, title: 'Complete profile setup', completed: true },
            { id: 2, title: 'Read company handbook', completed: true },
            { id: 3, title: 'Schedule mentor meeting', completed: true },
          ],
        },
        {
          id: '100008',
          title: 'Getting hooked on Slack',
          dateRange: 'Nov 21 23...Nov 22 23',
          progress: 0,
          status: 'pending',
          autoQA: 'Auto QA review: pending',
          tasks: [
            { id: 1, title: 'Join team channels', completed: false },
            { id: 2, title: 'Set up notifications', completed: false },
            { id: 3, title: 'Introduction message', completed: false },
          ],
        },
        {
          id: '100009',
          title: 'Deep dive into the intranet',
          dateRange: 'Nov 21 23...Nov 22 23',
          progress: 100,
          status: 'completed',
          tasks: [
            { id: 1, title: 'Navigate company resources', completed: true },
            { id: 2, title: 'Bookmark important pages', completed: true },
            { id: 3, title: 'Complete intranet quiz', completed: true },
          ],
        },
        {
          id: '100010',
          title: 'Introduction to mindsets (Grit and growth mindsets)',
          dateRange: 'Nov 22 23...Nov 24 23',
          progress: 0,
          status: 'not_started',
          tasks: [
            { id: 1, title: 'Watch mindset videos', completed: false },
            { id: 2, title: 'Complete reflection exercise', completed: false },
            { id: 3, title: 'Submit mindset assessment', completed: false },
          ],
        },
        {
          id: '1103',
          title: '0x00. Shell, navigation',
          dateRange: 'Nov 22 23...Dec 1 23',
          progress: 100,
          status: 'completed',
          tasks: [
            { id: 1, title: 'Basic shell commands', completed: true },
            { id: 2, title: 'File navigation exercises', completed: true },
            { id: 3, title: 'Shell scripting basics', completed: true },
          ],
        },
      ],
    },
    {
      id: 'frontend',
      name: 'Frontend Development',
      description: 'Modern web development with React and JavaScript',
      totalLessons: 8,
      completedLessons: 4,
      color: 'green',
      lessons: [
        {
          id: '200001',
          title: 'HTML & CSS Fundamentals',
          dateRange: 'Dec 1 23...Dec 8 23',
          progress: 100,
          status: 'completed',
          tasks: [
            { id: 1, title: 'Semantic HTML structure', completed: true },
            { id: 2, title: 'CSS Grid and Flexbox', completed: true },
            { id: 3, title: 'Responsive design project', completed: true },
          ],
        },
        {
          id: '200002',
          title: 'JavaScript ES6+ Features',
          dateRange: 'Dec 8 23...Dec 15 23',
          progress: 75,
          status: 'in_progress',
          tasks: [
            {
              id: 1,
              title: 'Arrow functions and destructuring',
              completed: true,
            },
            { id: 2, title: 'Promises and async/await', completed: true },
            { id: 3, title: 'ES6 modules project', completed: false },
          ],
        },
        {
          id: '200003',
          title: 'React Components & Props',
          dateRange: 'Dec 15 23...Dec 22 23',
          progress: 100,
          status: 'completed',
          tasks: [
            { id: 1, title: 'Functional components', completed: true },
            { id: 2, title: 'Props and state management', completed: true },
            { id: 3, title: 'Component composition', completed: true },
          ],
        },
        {
          id: '200004',
          title: 'React Hooks Deep Dive',
          dateRange: 'Dec 22 23...Dec 29 23',
          progress: 60,
          status: 'in_progress',
          tasks: [
            { id: 1, title: 'useState and useEffect', completed: true },
            { id: 2, title: 'Custom hooks creation', completed: true },
            { id: 3, title: 'Performance optimization', completed: false },
          ],
        },
        {
          id: '200005',
          title: 'State Management with Redux',
          dateRange: 'Jan 1 24...Jan 8 24',
          progress: 0,
          status: 'not_started',
          tasks: [
            { id: 1, title: 'Redux store setup', completed: false },
            { id: 2, title: 'Actions and reducers', completed: false },
            { id: 3, title: 'React-Redux integration', completed: false },
          ],
        },
        {
          id: '200006',
          title: 'Testing with Jest & React Testing Library',
          dateRange: 'Jan 8 24...Jan 15 24',
          progress: 0,
          status: 'not_started',
          tasks: [
            { id: 1, title: 'Unit testing components', completed: false },
            { id: 2, title: 'Integration testing', completed: false },
            { id: 3, title: 'Testing user interactions', completed: false },
          ],
        },
        {
          id: '200007',
          title: 'Performance Optimization',
          dateRange: 'Jan 15 24...Jan 22 24',
          progress: 0,
          status: 'locked',
          tasks: [
            {
              id: 1,
              title: 'Code splitting and lazy loading',
              completed: false,
            },
            { id: 2, title: 'Memoization techniques', completed: false },
            { id: 3, title: 'Bundle optimization', completed: false },
          ],
        },
        {
          id: '200008',
          title: 'Final Frontend Project',
          dateRange: 'Jan 22 24...Feb 1 24',
          progress: 0,
          status: 'locked',
          tasks: [
            { id: 1, title: 'Project planning and design', completed: false },
            { id: 2, title: 'Implementation and testing', completed: false },
            { id: 3, title: 'Deployment and presentation', completed: false },
          ],
        },
      ],
    },
    {
      id: 'backend',
      name: 'Backend Development',
      description: 'Server-side development with Node.js and databases',
      totalLessons: 6,
      completedLessons: 2,
      color: 'purple',
      lessons: [
        {
          id: '300001',
          title: 'Node.js Fundamentals',
          dateRange: 'Feb 1 24...Feb 8 24',
          progress: 100,
          status: 'completed',
          tasks: [
            { id: 1, title: 'Node.js runtime basics', completed: true },
            { id: 2, title: 'File system operations', completed: true },
            { id: 3, title: 'HTTP server creation', completed: true },
          ],
        },
        {
          id: '300002',
          title: 'Express.js Framework',
          dateRange: 'Feb 8 24...Feb 15 24',
          progress: 80,
          status: 'in_progress',
          tasks: [
            { id: 1, title: 'Express routing', completed: true },
            { id: 2, title: 'Middleware implementation', completed: true },
            { id: 3, title: 'Error handling', completed: false },
          ],
        },
        {
          id: '300003',
          title: 'Database Design & SQL',
          dateRange: 'Feb 15 24...Feb 22 24',
          progress: 0,
          status: 'not_started',
          tasks: [
            { id: 1, title: 'Database schema design', completed: false },
            { id: 2, title: 'SQL queries and joins', completed: false },
            { id: 3, title: 'Database optimization', completed: false },
          ],
        },
        {
          id: '300004',
          title: 'RESTful API Development',
          dateRange: 'Feb 22 24...Mar 1 24',
          progress: 0,
          status: 'not_started',
          tasks: [
            { id: 1, title: 'REST principles', completed: false },
            { id: 2, title: 'API endpoints creation', completed: false },
            { id: 3, title: 'API documentation', completed: false },
          ],
        },
        {
          id: '300005',
          title: 'Authentication & Authorization',
          dateRange: 'Mar 1 24...Mar 8 24',
          progress: 0,
          status: 'locked',
          tasks: [
            { id: 1, title: 'JWT implementation', completed: false },
            { id: 2, title: 'Role-based access control', completed: false },
            { id: 3, title: 'Security best practices', completed: false },
          ],
        },
        {
          id: '300006',
          title: 'Backend Project & Deployment',
          dateRange: 'Mar 8 24...Mar 15 24',
          progress: 0,
          status: 'locked',
          tasks: [
            { id: 1, title: 'Full-stack integration', completed: false },
            { id: 2, title: 'Cloud deployment', completed: false },
            { id: 3, title: 'Performance monitoring', completed: false },
          ],
        },
      ],
    },
    {
      id: 'devops',
      name: 'DevOps & Deployment',
      description: 'Infrastructure, CI/CD, and deployment strategies',
      totalLessons: 4,
      completedLessons: 0,
      color: 'orange',
      lessons: [
        {
          id: '400001',
          title: 'Git & Version Control Advanced',
          dateRange: 'Mar 15 24...Mar 22 24',
          progress: 0,
          status: 'not_started',
          tasks: [
            { id: 1, title: 'Branching strategies', completed: false },
            { id: 2, title: 'Merge conflicts resolution', completed: false },
            { id: 3, title: 'Code review processes', completed: false },
          ],
        },
        {
          id: '400002',
          title: 'Docker Containerization',
          dateRange: 'Mar 22 24...Mar 29 24',
          progress: 0,
          status: 'locked',
          tasks: [
            { id: 1, title: 'Docker fundamentals', completed: false },
            { id: 2, title: 'Container orchestration', completed: false },
            { id: 3, title: 'Multi-container applications', completed: false },
          ],
        },
        {
          id: '400003',
          title: 'CI/CD Pipelines',
          dateRange: 'Mar 29 24...Apr 5 24',
          progress: 0,
          status: 'locked',
          tasks: [
            { id: 1, title: 'GitHub Actions setup', completed: false },
            { id: 2, title: 'Automated testing', completed: false },
            { id: 3, title: 'Deployment automation', completed: false },
          ],
        },
        {
          id: '400004',
          title: 'Cloud Deployment & Monitoring',
          dateRange: 'Apr 5 24...Apr 12 24',
          progress: 0,
          status: 'locked',
          tasks: [
            { id: 1, title: 'Cloud platform setup', completed: false },
            { id: 2, title: 'Application monitoring', completed: false },
            { id: 3, title: 'Performance optimization', completed: false },
          ],
        },
      ],
    },
  ],

  // Overall progress analytics
  overallProgress: {
    totalLessons: 23,
    completedLessons: 9,
    inProgressLessons: 4,
    completionRate: 39,
    streak: 7,
    totalTasks: 69,
    completedTasks: 32,
  },
};
